openapi: 3.0.0
info:
  description: |
    Api dùng để tra cứu thời khóa biểu kma.
  version: "1.0.2"
  title: KMA Schedule API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: User
    description: Thông tin tài khoản sinh viên.
  - name: Schedule
    description: Thông tin về thời khóa biểu.
paths:
  /user:
    get:
      tags:
        - User
      summary: Lấy thông tin phiên đăng nhập.
      description: This can only be done by logged user.
      operationId: getUser
      responses:
        200:
          description: Information
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/User'
        404:
          description: User is not logged
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/ApiResponse'
  /user/login:
    post:
      tags:
        - User
      summary: Đăng nhập vào hệ thống
      operationId: loginUser
    #   produces:
    #      - application/json
      parameters:
        - in: query
          name: credentials
          description: Thông tin đăng nhập của sinh viên
          required: true
          schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Đăng nhập thành công
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - User
      summary: Đăng xuất khỏi hệ thống
      operationId: logoutUser
      responses:
        default:
          description: successful operation
# securitySchemes:
#     petstore_auth:
#       type: oauth2
#       flows:
#         implicit:
#           authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
#           scopes:
#             'write:pets': modify pets in your account
#             'read:pets': read your pets
#     api_key:
#       type: apiKey
#       name: api_key
#       in: header
components: 
  schemas:
    Login:
      type: object
      properties:
        studentCode:
          type: string
        password:
          type: string
    Schedule:
      type: object
      properties:
        subjectCode:
          type: string
        subjectName:
          type: string
        className:
          type: string
        teacher:
          type: string
        lesson:
          type: string
          description: Lesson study
          enum:
            - 1,2,3
            - 4,5,6
            - 7,8,9
            - 10,11,12
            - 13,14,15
        room:
          type: string
        day:
          type: string
          format: date-time        
      xml:
        name: Schedule
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        studentCode:
          type: string
        name:
          type: string
        gender:
          type: string
        className:
          type: string
      xml:
        name: User   
    ApiResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        studentCode:
          type: string
        name:
          type: string
        gender:
          type: string
        className:
          type: string
      xml:
        name: ApiResponse